version: '3.9'

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  clien-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  # products-api:
  #   build: ./products-api
  #   volumes:
  #     - ./products-api/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3001
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=file:./dev.db

  # orders-api:
  #   depends_on:
  #     - orders-db
  #   build: ./orders-api
  #   volumes:
  #     - ./orders-api/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3002
  #     - DATABASE_URL=postgresql://postgres:postgres@orders-db:5432/orders_database?schema=public
  #     - NATS_SERVERS=nats://nats-server:4222

  # orders-db:
  #   container_name: orders_database
  #   image: postgres:15.2
  #   restart: always
  #   volumes:
  #     - ./orders-api/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=orders_database
    